structures:
  departments:
    type: hashmap
    key: dept_id
    materialize: from_data
    data:
      - { dept_id: "eng",   dept_name: "Engineering" }
      - { dept_id: "sales", dept_name: "Sales" }

pipeline:
  - join:
      on: dept_id
      using: departments
  - project:
      - "left.user"
      - "right.dept_name"

